### PR TITLE
Add `flake.nix`-based reproducible builds

### PR DESCRIPTION
**Pull request by dpc**
I prepared this change on top of rocksdb branch which enabled rocksdb. I do not include that change in this PR though, to keep these things separate.

Building in `nix develop` works, but `nix build -L ...` is currently broken due to https://github.com/ipetkov/crane/issues/111 (will try to follow up with a fix as soon as crane is fixed upstream).

Included README should explain how to use.

### CODE REVIEW

**Comment by futurepaul** [comment]
this is exciting, what would be a good way for me to test this out?

**Comment by dpc** [comment]
I wrote a README and then forgot to commit it. :facepalm: . See if it helps.

**Comment by dpc** [comment]
I might have some improvements soon, so let's hold with landing it.

**Comment by dpc** [comment]
OK. Made it work more properly (AFAICT) and added support for C++. This also works with compiling rocksdb, which will be included in another PR by @justinmoon

**Comment by dpc** [comment]
https://github.com/rust-rocksdb/rust-rocksdb/pull/682 breaks rocksdb on 32bit archs

**Comment by dpc** [comment]
Just to avoid confusion: I prepared this change on top of `rocksdb` branch which enabled rocksdb. I do not include that change in this PR though, to keep these things separate.

**Comment by justinmoon** [comment]
`nix develop` fails on m1 Mac with `error: No Android SDK tarballs are available for system architecture: aarch64-darwin`

**Comment by dpc** [comment]
@justinmoon Do we want to land it?

**Comment by justinmoon** [comment]
Looks like I forgot to comment here.

AFAICT this doesn't really help because rust code is built as a side-effect of running `flutter run` or `flutter build` via http://cjycode.com/flutter_rust_bridge/. I think it would probably be better to have the `flake.nix` in the root of the project for this reason. Let me revisit this today and try to get it working.

**Pull request merged**
